# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('reply_count', models.CharField(max_length=2014)),
                ('url', models.CharField(max_length=1024)),
                ('base_url', models.CharField(max_length=1024)),
                ('node', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'v2ex',
            },
        ),
    ]
